"""empty message

Revision ID: 14bb92d39fd4
Revises: 6c4aa7201263
Create Date: 2016-07-16 13:38:37.051550

"""

# revision identifiers, used by Alembic.
revision = '14bb92d39fd4'
down_revision = '6c4aa7201263'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('pubd', sa.DateTime(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('note', sa.UnicodeText(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('attribute', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.UnicodeText(), nullable=True),
    sa.Column('seoKey', sa.String(length=64), nullable=True),
    sa.Column('seoDescription', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_attribute'), 'articles', ['attribute'], unique=False)
    op.create_index(op.f('ix_articles_pubd'), 'articles', ['pubd'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_pubd'), table_name='articles')
    op.drop_index(op.f('ix_articles_attribute'), table_name='articles')
    op.drop_table('articles')
    ### end Alembic commands ###
