"""empty message

Revision ID: 211bfe0ca599
Revises: 7da38d5f39da
Create Date: 2016-07-16 13:36:30.167551

"""

# revision identifiers, used by Alembic.
revision = '211bfe0ca599'
down_revision = '7da38d5f39da'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('pubd', sa.DateTime(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('note', sa.UnicodeText(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('attribute', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.UnicodeText(), nullable=True),
    sa.Column('seoKey', sa.String(length=64), nullable=True),
    sa.Column('seoDescription', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Articles_attribute'), 'Articles', ['attribute'], unique=False)
    op.create_index(op.f('ix_Articles_pubd'), 'Articles', ['pubd'], unique=False)
    op.create_index(op.f('ix_Articles_title'), 'Articles', ['title'], unique=False)
    op.create_index(op.f('ix_Articles_url'), 'Articles', ['url'], unique=False)
    op.drop_table('archives')
    op.add_column('sysinfo', sa.Column('webnote', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sysinfo', 'webnote')
    op.create_table('archives',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('show', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('pubd', mysql.DATETIME(), nullable=True),
    sa.Column('click', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('attribute', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('thumbnail', mysql.TEXT(), nullable=True),
    sa.Column('seoKey', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('seoDescription', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_Articles_url'), table_name='Articles')
    op.drop_index(op.f('ix_Articles_title'), table_name='Articles')
    op.drop_index(op.f('ix_Articles_pubd'), table_name='Articles')
    op.drop_index(op.f('ix_Articles_attribute'), table_name='Articles')
    op.drop_table('Articles')
    ### end Alembic commands ###
