"""empty message

Revision ID: 7da38d5f39da
Revises: 9699c851bb1a
Create Date: 2016-07-13 23:54:07.595226

"""

# revision identifiers, used by Alembic.
revision = '7da38d5f39da'
down_revision = '9699c851bb1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('url', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archives', 'url')
    ### end Alembic commands ###
