"""empty message

Revision ID: 9699c851bb1a
Revises: 7d5efddd092b
Create Date: 2016-07-11 10:49:03.529764

"""

# revision identifiers, used by Alembic.
revision = '9699c851bb1a'
down_revision = '7d5efddd092b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navcats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('pubd', sa.DateTime(), nullable=True),
    sa.Column('attr', sa.Integer(), nullable=False),
    sa.Column('nlink', sa.String(length=64), nullable=True),
    sa.Column('html', sa.String(length=64), nullable=False),
    sa.Column('note', sa.UnicodeText(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('seoKey', sa.String(length=64), nullable=True),
    sa.Column('seoDescription', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('navcats')
    ### end Alembic commands ###
